// <auto-generated />
namespace qlTiecCuoi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<< HEAD:qlTiecCuoi/Migrations/202006061156579_initData.Designer.cs
    public sealed partial class initData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initData));
        
        string IMigrationMetadata.Id
        {
            get { return "202006061156579_initData"; }
=======
    public sealed partial class danhsachsanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(danhsachsanh));
        
        string IMigrationMetadata.Id
        {
            get { return "202006061834286_danhsachsanh"; }
>>>>>>> 7bc1d0c923584e6fbc290cc4f40f5de1faaad08f:qlTiecCuoi/Migrations/202006061834286_danhsachsanh.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
