// <auto-generated />
namespace qlTiecCuoi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hinhanh_monan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hinhanh_monan));
        
        string IMigrationMetadata.Id
        {
            get { return "202006031550521_hinhanh_monan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
